export const TestTableData = [
  // {
  //   id: 3,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 4,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 5,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 6,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 13,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 14,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 15,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 16,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 23,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 24,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 25,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
  // {
  //   id: 26,
  //   purchaseDate: "2021-05-10",
  //   storeName: "abc",
  //   total: "22.00",
  //   buyer: "Me",
  //   meToPay: "",
  //   themToPay: "10.50",
  //   myDeductions: {
  //     list: ["11.00"],
  //     inputValue: 0,
  //     sum: 11,
  //   },
  //   theirDeductions: {
  //     list: ["10.00"],
  //     inputValue: 0,
  //     sum: 10,
  //   },
  // },
];
